# Generated by Django 4.1 on 2022-08-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verify",
            field=models.BooleanField(default=False),
        ),
    ]
